vms:
  - name: myfedora
    cpu: 1
    memory: 2Gi

    # type could be masquerade (Pod Networking) or bridge (other CNI or OVN-K overlay)
    networks:
      - name: default
        type: masquerade

      - name: sa-manager
        type: bridge
  
      - name: sa-production
        type: bridge

    disks:
      - name: rootdisk
        # support option: pvc, image, blank
        type: image
        size: 30Gi
        datasourceName: fedora
        datasourceNamespace: openshift-virtualization-os-images

      - name: secondary
        type: blank
        size: 30Gi
        storageclassName: ocs-external-storagecluster-ceph-rbd

nads:
  - name: sa-manager
  - name: sa-production

# TODO
# 1. Add cloud init script
# 2. Network should have default pod network
# 3. Disk as parameter and need support datavolume from snapshot
# 4. Support windows in the same helm