# vms:
#   fedora01:
#     os: linux
#     cpu: 1
#     memory: 2Gi
#     networks:
#       - name: default
#         type: masquerade
#       - name: sa-manager
#         type: bridge
#       - name: sa-production
#         type: bridge
#     disks:
#       - name: rootdisk
#         type: image
#         size: 30Gi
#         datasourceName: fedora
#         datasourceNamespace: openshift-virtualization-os-images
#     cloudinit: |-
#       #cloud-config
#       user: fedora
#       password: redhat1!
#       chpasswd: { expire: False }
# nads:
#   - name: sa-manager
#   - name: sa-production
