---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - rolebinding.yaml
  - denyall.yaml

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
  - name: linux-vm
    releaseName: myfedora
    namespace: p300
    valuesFile: values.yaml