apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-dv-clone
  namespace: test01
subjects:
- kind: ServiceAccount
  name: default
  namespace: test02
roleRef:
  kind: ClusterRole
  name: dv-cloner 
  apiGroup: rbac.authorization.k8s.io