vms:
  fedora01:
    cpu: 1
    memory: 2Gi
    networks:
      - name: default
        type: masquerade
      - name: sa-manager
        type: bridge
      - name: sa-production
        type: bridge
    disks:
      - name: rootdisk
        type: image
        size: 30Gi
        datasourceName: fedora
        datasourceNamespace: openshift-virtualization-os-images
  fedora02:
    cpu: 1
    memory: 2Gi
    networks:
      - name: default
        type: masquerade
      - name: sa-manager
        type: bridge
      - name: sa-production
        type: bridge
    disks:
      - name: rootdisk
        type: image
        size: 30Gi
        datasourceName: fedora
        datasourceNamespace: openshift-virtualization-os-images
nads:
  - name: sa-manager
  - name: sa-production

# TODO
# 1. Add cloud init script
# 2. Network should have default pod network
# 3. Disk as parameter and need support datavolume from snapshot
# 4. Support windows in the same helm