apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: {{ .Release.Name }}
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: RerunOnFailure
  template:
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: {{ .Values.cpu }}
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
          {{- range .Values.networks }}
            - name: {{ .name }}
              {{- if eq .type "bridge" }}
              bridge: {}
              {{- else }}
              masquerade: {}
              {{- end }}
              model: virtio
          {{- end }}
        memory:
          guest: {{ .Values.memory }}
      networks:
      {{- range .Values.networks }}
        {{- if eq .type "bridge" }}
        - multus:
            networkName: {{ .name }}
          name: {{ .name }}
        {{- else }}
        - name: {{ .name }}
          pod: {}
        {{- end }}
          model: virtio
      {{- end }}
      volumes:
        - dataVolume:
            name: {{ .Release.Name }}
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: redhat
              chpasswd: { expire: False }
          name: cloudinitdisk