---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../templates/vapp

helmCharts:
  - name: linux-vm
    releaseName: myfedora
    namespace: test03
    valuesInline:
      fedora01:
        cpu: 2