---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../templates/vapp

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
  - name: linux-vm
    releaseName: myfedora
    namespace: test04
    valuesMerge: replace
    valuesInline:
      fedora01:
        cpu: 2