---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../templates/vapp

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
  - name: linux-vm
    releaseName: myfedora
    namespace: test03