---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../templates/vapp/

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
  - name: linux-vm
    releaseName: myfedora
    namespace: p300
    valuesFile: ../../templates/vapp/values.yaml
    valuesInline:
      vms:
        fedora01:
          cpu: 2

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: p300
    target:
      kind: Rolebinding
