{{- range .Values.nads }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .name }}-{{ $.Release.Namespace }}
  namespace: {{ $.Release.Namespace }}
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "{{ .name }}-{{ $.Release.Namespace }}",
        "type": "ovn-k8s-cni-overlay",
        "netAttachDefName": "{{ $.Release.Namespace }}/{{ .name }}-{{ $.Release.Namespace }}",
        "topology": "layer2"
    }
{{- end }}