{{- range $key,$val := .Values.vms }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  dataVolumeTemplates:
    {{- range $val.disks }}
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: {{ $key }}-{{ .name }}
      spec:
        {{- if eq .type "image" }}
        sourceRef:
          kind: DataSource
          name: {{ .datasourceName }}
          namespace: {{ .datasourceNamespace }}
        storage:
          resources:
            requests:
              storage: {{ .size }}
        {{- else if eq .type "pvc" }}
        source:
          pvc:
            name: {{ .datasourceName }}
            namespace: {{ .datasourceNamespace }}
        storage:
          resources:
            requests:
              storage: {{ .size }}
        {{- else if eq .type "blank" }}
        source:
          blank: {}
        storage:
          resources:
            requests:
               storage: {{ .size }}
          storageClassName: {{ .storageclassName }}
        {{- end }}
    {{- end }}
  runStrategy: RerunOnFailure
  template:
    spec:
      architecture: amd64
      domain:
        {{- if eq $val.os "windows" }}
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              persistent: true
              secureBoot: true
        {{- end }}
        cpu:
          cores: 1
          sockets: {{ $val.cpu }}
          threads: 1
        devices:
          {{- if eq $val.os "windows" }}
          logSerialConsole: false
          tpm:
            persistent: true
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          {{- end }}
          disks:
            {{- range $val.disks }}
            - disk:
                {{- if eq $val.os "windows" }}
                bus: sata
                {{- else if eq $val.os "linux" }}
                bus: virtio
                {{- end }}
              name: {{ .name }}
            {{- end }}
            {{- if eq $val.os "windows" }}
            - cdrom:
                bus: sata
              name: windows-drivers-disk
            {{- else if eq $val.os "linux" }}
            - disk:
                bus: virtio
              name: cloudinitdisk
            {{- end }}
          interfaces:
          {{- range $val.networks }}
            {{- if eq .type "bridge" }}
            - name: {{ .name }}
              model: virtio
              bridge: {}
            {{- else if eq .os "windows" }}
            - name: {{ .name }}
              model: e1000e
              masquerade: {}
            {{- else }}
            - name: {{ .name }}
              model: virtio
              masquerade: {}
            {{- end }}
          {{- end }}
        memory:
          guest: {{ $val.memory }}
      networks:
      {{- range $val.networks }}
        {{- if eq .type "bridge" }}
        - multus:
            networkName: {{ .name }}-{{ $.Release.Namespace }}
          name: {{ .name }}
        {{- else }}
        - name: {{ .name }}
          pod: {}
        {{- end }}
      {{- end }}
      volumes:
        {{- range $val.disks }}
        {{- if eq .name "rootdisk" }}
        - dataVolume:
            name: {{ $key }}-{{ .name }}
          name: rootdisk
        {{- else }}
        - dataVolume:
            name: {{ $key }}-{{ .name }}
          name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- if eq $val.os "windows" }}
        - containerDisk:
            image: 'registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:07dbdd6c8893619bbda5fd6a9224e0a50555c126fae3d82c83041ad146cecf0b'
          name: windows-drivers-disk
        {{- else if eq $val.os "linux" }}
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: redhat1!
              chpasswd: { expire: False }
          name: cloudinitdisk
        {{- end }}
{{- end }}